# Flutter build
name: $(Date:yyyyMMdd)$(Rev:r)
variables:
  projectDirectory: 'Novus Trade'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'custom'
        customVersion: '1.17.5'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: $(System.DefaultWorkingDirectory)
  
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksignerKeystoreFile: 'key.jks'
        apksignerKeystorePassword: '123456'
        apksignerKeystoreAlias: 'key'
        apksignerKeyPassword: '123456'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1