name: novus_trade_v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  carousel_slider: ^4.0.0
  adobe_xd: ^2.0.0+1
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  sticky_headers: ^0.2.0
  smooth_star_rating: ^1.1.1
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^0.21.0+1
  flutter_bloc: ^7.1.0
  http: ^0.13.4
  dio: ^4.0.0
  async: ^2.4.2
  shared_preferences: ^2.0.8
  dio_http_cache: ^0.3.0
  provider: ^6.0.1
  auto_size_text: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  easy_localization: ^3.0.0
  json_serializable: ^4.1.4

  freezed: ^0.14.2

  badges: ^2.0.1

  flutter_html: ^2.0.0-nullsafety.0
dev_dependencies:
  build_runner: ^2.1.4
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/translations/en-US.json
    - lib/translations/vi-VN.json
    - lib/translations/fr-FR.json
    - img/images/
    - img/onboarding0.png
    - img/onboarding1.png
    - img/onboarding2.png
    - img/onboarding3.png
    - img/twitter.png
    - img/facebook.png
    - img/google-plus.png
    - img/linkedin.png
    - img/user1.jpg
    - img/banner_sale.png
    - img/user2.jpg
    - img/user3.jpg
    - img/user0.jpg
    - img/visa.png
    - img/paypal.png
    - img/apple_pay.png
    - img/brazil.png
    - img/canada.png
    - img/china.png
    - img/france.png
    - img/germany.png
    - img/italy.png
    - img/netherlands.png
    - img/spain.png
    - img/united-arab-emirates.png
    - img/united-states-of-america.png
    - img/marker.png
    - img/pro1.webp
    - img/pro2.webp
    - img/pro3.webp
    - img/pro4.webp
    - img/pro5.webp
    - img/pro6.webp
    - img/pro7.webp
    - img/man1.webp
    - img/man2.webp
    - img/man3.webp
    - img/man4.webp
    - img/man5.webp
    - img/man6.webp
    - img/man7.webp
    - img/man8.webp
    - img/baby1.webp
    - img/baby2.webp
    - img/baby3.webp
    - img/baby4.webp
    - img/baby5.webp
    - img/baby6.webp
    - img/home1.webp
    - img/home2.webp
    - img/home3.webp
    - img/home4.webp
    - img/home5.webp
    - img/home6.webp
    - img/home7.webp
    - img/home8.webp
    - img/home9.webp
    - img/home10.webp
    - img/home11.webp
    - img/sport1.webp
    - img/sport2.webp
    - img/sport3.webp
    - img/sport4.webp
    - img/sport5.webp
    - img/sport6.webp
    - img/sport7.webp
    - img/loading.gif
    - img/sport8.webp
    - img/sport9.webp
    - img/sport10.webp
    - img/watch1.webp
    - img/watch2.webp
    - img/watch3.webp
    - img/watch4.webp
    - img/watch5.webp
    - img/watch6.webp
    - img/watch7.webp
    - img/watch8.webp
    - img/watch9.webp
    - img/acer.svg
    - img/apple.svg
    - img/casio.svg
    - img/samsung.svg
    - img/xerox.svg
    - img/nikon.svg
    - img/intel.svg
    - img/huawei.svg
    - img/gopro.svg
    - img/hp.svg
    - img/logo-03.svg
    - img/logo-04.svg
    - img/logo-05.svg
    - img/logo-06.svg
    - img/logo-07.svg
    - img/logo-08.svg
    - img/logo-09.svg
    - img/logo-10.svg
    - img/logo-11.svg
    - img/slider1.jpg
    - img/slider2.jpg
    - img/slider3.jpg
  fonts:
    - family: EcommerceAppUI
      fonts:
        - asset: fonts/EcommerceAppUI.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
